// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCompany.Intranet.Data;

#nullable disable

namespace MyCompany.Intranet.Migrations
{
    [DbContext(typeof(MyCompanyIntranetContext))]
    partial class MyCompanyIntranetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyCompany.Intranet.Models.Warehouse.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCategory");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            IdCategory = 1,
                            Description = "Electronic devices",
                            Name = "Electronics"
                        },
                        new
                        {
                            IdCategory = 2,
                            Description = "Food products",
                            Name = "Food"
                        },
                        new
                        {
                            IdCategory = 3,
                            Description = "Workshop tools",
                            Name = "Tools"
                        });
                });

            modelBuilder.Entity("MyCompany.Intranet.Models.Warehouse.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployee"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdWarehouse")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEmployee");

                    b.HasIndex("IdWarehouse");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            IdEmployee = 1,
                            FirstName = "John",
                            IdWarehouse = 1,
                            LastName = "Smith",
                            Position = "Manager"
                        },
                        new
                        {
                            IdEmployee = 2,
                            FirstName = "Anna",
                            IdWarehouse = 2,
                            LastName = "Kowalska",
                            Position = "Worker"
                        },
                        new
                        {
                            IdEmployee = 3,
                            FirstName = "Mike",
                            IdWarehouse = 3,
                            LastName = "Brown",
                            Position = "Supervisor"
                        });
                });

            modelBuilder.Entity("MyCompany.Intranet.Models.Warehouse.Inventory", b =>
                {
                    b.Property<int>("IdInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInventory"));

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<int>("IdWarehouse")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdInventory");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdWarehouse");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            IdInventory = 1,
                            IdProduct = 1,
                            IdWarehouse = 1,
                            Quantity = 10
                        },
                        new
                        {
                            IdInventory = 2,
                            IdProduct = 2,
                            IdWarehouse = 3,
                            Quantity = 200
                        },
                        new
                        {
                            IdInventory = 3,
                            IdProduct = 3,
                            IdWarehouse = 2,
                            Quantity = 50
                        });
                });

            modelBuilder.Entity("MyCompany.Intranet.Models.Warehouse.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<int>("IdSupplier")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdOrder");

                    b.HasIndex("IdSupplier");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            IdOrder = 1,
                            IdSupplier = 1,
                            OrderDate = new DateTime(2022, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "New"
                        },
                        new
                        {
                            IdOrder = 2,
                            IdSupplier = 2,
                            OrderDate = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered"
                        },
                        new
                        {
                            IdOrder = 3,
                            IdSupplier = 3,
                            OrderDate = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("MyCompany.Intranet.Models.Warehouse.OrderItem", b =>
                {
                    b.Property<int>("IdOrderItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrderItem"));

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdOrderItem");

                    b.HasIndex("IdOrder");

                    b.HasIndex("IdProduct");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            IdOrderItem = 1,
                            IdOrder = 1,
                            IdProduct = 1,
                            PurchasePrice = 4200m,
                            Quantity = 2
                        },
                        new
                        {
                            IdOrderItem = 2,
                            IdOrder = 2,
                            IdProduct = 2,
                            PurchasePrice = 4.80m,
                            Quantity = 100
                        },
                        new
                        {
                            IdOrderItem = 3,
                            IdOrder = 3,
                            IdProduct = 3,
                            PurchasePrice = 20m,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("MyCompany.Intranet.Models.Warehouse.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProduct");

                    b.HasIndex("IdCategory");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            IdProduct = 1,
                            Description = "Gaming laptop",
                            IdCategory = 1,
                            Name = "Laptop",
                            Price = 4500m
                        },
                        new
                        {
                            IdProduct = 2,
                            Description = "Whole grain bread",
                            IdCategory = 2,
                            Name = "Bread",
                            Price = 5.50m
                        },
                        new
                        {
                            IdProduct = 3,
                            Description = "Steel hammer",
                            IdCategory = 3,
                            Name = "Hammer",
                            Price = 25.99m
                        });
                });

            modelBuilder.Entity("MyCompany.Intranet.Models.Warehouse.Supplier", b =>
                {
                    b.Property<int>("IdSupplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSupplier"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdSupplier");

                    b.ToTable("Supplier");

                    b.HasData(
                        new
                        {
                            IdSupplier = 1,
                            Email = "tech@supply.com",
                            Name = "TechSupply",
                            Phone = "111-222-333"
                        },
                        new
                        {
                            IdSupplier = 2,
                            Email = "food@corp.com",
                            Name = "FoodCorp",
                            Phone = "444-555-666"
                        },
                        new
                        {
                            IdSupplier = 3,
                            Email = "tools@master.com",
                            Name = "ToolMaster",
                            Phone = "777-888-999"
                        });
                });

            modelBuilder.Entity("MyCompany.Intranet.Models.Warehouse.Warehouse", b =>
                {
                    b.Property<int>("IdWarehouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWarehouse"));

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdWarehouse");

                    b.ToTable("Warehouse");

                    b.HasData(
                        new
                        {
                            IdWarehouse = 1,
                            Location = "Warsaw",
                            Name = "Main Warehouse"
                        },
                        new
                        {
                            IdWarehouse = 2,
                            Location = "Krakow",
                            Name = "Backup Warehouse"
                        },
                        new
                        {
                            IdWarehouse = 3,
                            Location = "Lodz",
                            Name = "Food Storage"
                        });
                });

            modelBuilder.Entity("MyCompany.Intranet.Models.Warehouse.Employee", b =>
                {
                    b.HasOne("MyCompany.Intranet.Models.Warehouse.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("IdWarehouse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MyCompany.Intranet.Models.Warehouse.Inventory", b =>
                {
                    b.HasOne("MyCompany.Intranet.Models.Warehouse.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyCompany.Intranet.Models.Warehouse.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("IdWarehouse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MyCompany.Intranet.Models.Warehouse.Order", b =>
                {
                    b.HasOne("MyCompany.Intranet.Models.Warehouse.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("IdSupplier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MyCompany.Intranet.Models.Warehouse.OrderItem", b =>
                {
                    b.HasOne("MyCompany.Intranet.Models.Warehouse.Order", "Order")
                        .WithMany()
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyCompany.Intranet.Models.Warehouse.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyCompany.Intranet.Models.Warehouse.Product", b =>
                {
                    b.HasOne("MyCompany.Intranet.Models.Warehouse.Category", "Category")
                        .WithMany()
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
